version: "3.2"
services:
  duckdns:
#    image: ghcr.io/linuxserver/duckdns:latest
    build:
      dockerfile: dockerfile.duckdns
    image: duckdns
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=$PUID_DUCK         #optional
      - PGID=$PGID_DUCK         #optional
      - TZ=$TIMEZONE            #optional
      - SUBDOMAINS=$SUB_DOMAINS
      - TOKEN=$TOKEN
      - UPDATE_IP=$UPDATE_IP    #optional
      - LOG_FILE=$LOGFILE_FLAG  #optional
    volumes:
      - vol_duckdns:/config     #optional
    restart: unless-stopped

volumes:
  vol_duckdns:
